### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by raypatterson** [eclifford/logr#1]
Hi @eclifford,

I'd like to use your logger in an app code base that renders on the server and client, however since it's only available as a Bower component it's a little hard to import using `require` in Node unless I migrate it into my app JS somehow.

Have you considered publishing to NPM?

Thanks!

**Comment by eclifford** [comment]
I'll look into this and get back to you.

**Comment by eclifford** [comment]
@RayPatterson I've released a a new minor version. I had to change a few things around to support Node's global console object. Let me know what you think.

https://www.npmjs.com/package/logr.js

**Comment by raypatterson** [comment]
Thanks Eric, I needed to add `"main": "logr.js"` to the package.json for `require` to be able to find the JS file, but then it worked fine. The dynamic logs are really a step up from what I was working with before!

**Comment by eclifford** [comment]
Thanks Ray, I'll patch that up as well.

FYI I also have silently released a Chrome Browser plugin that adds a tab to the dev tools for easily setting the Log levels for all logs detected on a given page. 

https://chrome.google.com/webstore/detail/logr/baeanbiibajakocmgnnoadgljmnknonp

**Comment by raypatterson** [comment]
Cool! Added the plugin!
